sudo: required
services:
  - docker

before_install:
  - docker build -t bolatito/reatapp:latest -f Dockerfile.dev .

script:
  - docker run bolatito/reatapp npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-139912354378"
  bucket_path: "reactapp"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
